services:
  chat:
    ports:
      - "3000:3000"
    image: epam/ai-dial-chat:0.10.0
    environment:
      AUTH_KEYCLOAK_HOST: "http://host.docker.internal:8080/realms/dial"
      AUTH_KEYCLOAK_CLIENT_ID: "dial-chat"
      AUTH_KEYCLOAK_SECRET: ""
      NEXTAUTH_SECRET: "secret"
      DIAL_API_HOST: "http://host.docker.internal:8081"
      DIAL_API_KEY: "dial_api_key"
      ENABLED_FEATURES: "conversations-section,prompts-section,top-settings,top-clear-conversation,top-chat-info,top-chat-model-settings,empty-chat-settings,header,footer,request-api-key,report-an-issue,likes,input-files,attachments-manager"

  redis:
    image: redis:7.2.4-alpine3.19
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 2000mb
      --maxmemory-policy volatile-lfu
      --save ""
      --appendonly no
      --loglevel warning
    mem_limit: 2200M

  echo:
    build: echo
    ports:
      - "5000:5000"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    ports:
      - "8080:8080"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
